#!/bin/sh
java -jar /Users/korol/Sites/asl.loc/src/public/js/src/compiler.jar --js /Users/korol/Sites/asl.loc/src/public/js/src/assol.calendar.js               --js_output_file /Users/korol/Sites/asl.loc/src/public/js/assol.calendar.js
java -jar /Users/korol/Sites/asl.loc/src/public/js/src/compiler.jar --js /Users/korol/Sites/asl.loc/src/public/js/src/assol.customer.card.js          --js_output_file /Users/korol/Sites/asl.loc/src/public/js/assol.customer.card.js
java -jar /Users/korol/Sites/asl.loc/src/public/js/src/compiler.jar --js /Users/korol/Sites/asl.loc/src/public/js/src/assol.customer.list.js          --js_output_file /Users/korol/Sites/asl.loc/src/public/js/assol.customer.list.js
java -jar /Users/korol/Sites/asl.loc/src/public/js/src/compiler.jar --js /Users/korol/Sites/asl.loc/src/public/js/src/assol.document.js               --js_output_file /Users/korol/Sites/asl.loc/src/public/js/assol.document.js
java -jar /Users/korol/Sites/asl.loc/src/public/js/src/compiler.jar --js /Users/korol/Sites/asl.loc/src/public/js/src/assol.employee.card.js          --js_output_file /Users/korol/Sites/asl.loc/src/public/js/assol.employee.card.js
java -jar /Users/korol/Sites/asl.loc/src/public/js/src/compiler.jar --js /Users/korol/Sites/asl.loc/src/public/js/src/assol.employee.list.js          --js_output_file /Users/korol/Sites/asl.loc/src/public/js/assol.employee.list.js
java -jar /Users/korol/Sites/asl.loc/src/public/js/src/compiler.jar --js /Users/korol/Sites/asl.loc/src/public/js/src/assol.news.js                   --js_output_file /Users/korol/Sites/asl.loc/src/public/js/assol.news.js
java -jar /Users/korol/Sites/asl.loc/src/public/js/src/compiler.jar --js /Users/korol/Sites/asl.loc/src/public/js/src/assol.report.director.js        --js_output_file /Users/korol/Sites/asl.loc/src/public/js/assol.report.director.js
java -jar /Users/korol/Sites/asl.loc/src/public/js/src/compiler.jar --js /Users/korol/Sites/asl.loc/src/public/js/src/assol.report.list.director.js   --js_output_file /Users/korol/Sites/asl.loc/src/public/js/assol.report.list.director.js
java -jar /Users/korol/Sites/asl.loc/src/public/js/src/compiler.jar --js /Users/korol/Sites/asl.loc/src/public/js/src/assol.report.list.translate.js  --js_output_file /Users/korol/Sites/asl.loc/src/public/js/assol.report.list.translate.js
java -jar /Users/korol/Sites/asl.loc/src/public/js/src/compiler.jar --js /Users/korol/Sites/asl.loc/src/public/js/src/assol.report.translate.js       --js_output_file /Users/korol/Sites/asl.loc/src/public/js/assol.report.translate.js
java -jar /Users/korol/Sites/asl.loc/src/public/js/src/compiler.jar --js /Users/korol/Sites/asl.loc/src/public/js/src/assol.services.js               --js_output_file /Users/korol/Sites/asl.loc/src/public/js/assol.services.js
java -jar /Users/korol/Sites/asl.loc/src/public/js/src/compiler.jar --js /Users/korol/Sites/asl.loc/src/public/js/src/assol.system.events.js          --js_output_file /Users/korol/Sites/asl.loc/src/public/js/assol.system.events.js
java -jar /Users/korol/Sites/asl.loc/src/public/js/src/compiler.jar --js /Users/korol/Sites/asl.loc/src/public/js/src/assol.task.js                   --js_output_file /Users/korol/Sites/asl.loc/src/public/js/assol.task.js
java -jar /Users/korol/Sites/asl.loc/src/public/js/src/compiler.jar --js /Users/korol/Sites/asl.loc/src/public/js/src/assol.training.article.js       --js_output_file /Users/korol/Sites/asl.loc/src/public/js/assol.training.article.js
java -jar /Users/korol/Sites/asl.loc/src/public/js/src/compiler.jar --js /Users/korol/Sites/asl.loc/src/public/js/src/assol.training.js               --js_output_file /Users/korol/Sites/asl.loc/src/public/js/assol.training.js
java -jar /Users/korol/Sites/asl.loc/src/public/js/src/compiler.jar --js /Users/korol/Sites/asl.loc/src/public/js/src/style-scripts.js                --js_output_file /Users/korol/Sites/asl.loc/src/public/js/style-scripts.js
java -jar /Users/korol/Sites/asl.loc/src/public/js/src/compiler.jar --js /Users/korol/Sites/asl.loc/src/public/js/src/utils.js                        --js_output_file /Users/korol/Sites/asl.loc/src/public/js/utils.js

java -jar /Users/korol/Sites/asl.loc/src/public/js/src/compiler.jar --js /Users/korol/Sites/asl.loc/src/public/js/src/lovestory.task.js                   --js_output_file /Users/korol/Sites/asl.loc/src/public/js/lovestory.task.js
java -jar /Users/korol/Sites/asl.loc/src/public/js/src/compiler.jar --js /Users/korol/Sites/asl.loc/src/public/js/src/lovestory.report.director.js        --js_output_file /Users/korol/Sites/asl.loc/src/public/js/lovestory.report.director.js
java -jar /Users/korol/Sites/asl.loc/src/public/js/src/compiler.jar --js /Users/korol/Sites/asl.loc/src/public/js/src/lovestory.report.list.director.js   --js_output_file /Users/korol/Sites/asl.loc/src/public/js/lovestory.report.list.director.js
java -jar /Users/korol/Sites/asl.loc/src/public/js/src/compiler.jar --js /Users/korol/Sites/asl.loc/src/public/js/src/lovestory.report.list.translate.js  --js_output_file /Users/korol/Sites/asl.loc/src/public/js/lovestory.report.list.translate.js
java -jar /Users/korol/Sites/asl.loc/src/public/js/src/compiler.jar --js /Users/korol/Sites/asl.loc/src/public/js/src/lovestory.report.translate.js       --js_output_file /Users/korol/Sites/asl.loc/src/public/js/lovestory.report.translate.js